[package]
name = "trie-match"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = "1"
quote = "1"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "match"
harness = false
