name: build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.70.0 # MSRV
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install ${{ matrix.rust }}
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component rustfmt,clippy
          rustup default ${{ matrix.rust }}

      - name: Run cargo check
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo check

      - name: Run cargo fmt
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo fmt -- --check

      - name: Run cargo clippy
        # Run clippy only on stable to ignore unreasonable old warnings.
        continue-on-error: ${{ matrix.rust != 'stable' }}
        run: cargo clippy -- -D warnings -W clippy::nursery -W clippy::pedantic

      - name: Run cargo test
        run: cargo test

      - name: Run cargo test all features
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo test --all-features

      - name: Run cargo doc
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo doc --release --all-features
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable

      - name: Run cargo publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
